"""Integrator agent: branch, commit, and open a PR for the generated app."""

from __future__ import annotations

from autopilot.agents.base import journal, workspace_for
from autopilot.tools import git


def integrate_node(state: dict) -> dict:
    ws = workspace_for(state)
    spec = state.get("spec", {})
    run_id = state.get("run_id", "run")
    branch = f"autopilot/{spec.get('name', 'app')}-{run_id[:8]}"

    body = (
        f"Autonomously generated by BAX Autopilot.\n\n"
        f"**Intent:** {state.get('intent','')}\n\n"
        f"**Tests:** {'PASS' if state.get('test_ok') else 'FAIL'}\n"
        f"**Review:** {'APPROVED' if state.get('review_ok') else 'N/A'}\n"
        f"**Terraform:** {'ok' if state.get('deploy_ok') else 'see report'}\n\n"
        f"Services: {', '.join(s.get('name','') for s in state.get('services', []))}\n"
    )

    result = git.init_commit_pr(
        ws.root,
        branch=branch,
        title=f"feat: {spec.get('name', 'app')} — {spec.get('summary', '')}"[:100],
        body=body,
    )

    return {
        "pr_url": result.pr_url,
        "phase": "done",
        "status": "done",
        "steps": state.get("steps", 0) + 1,
        **journal(
            f"integrate: branch={result.branch} committed={result.committed} "
            f"pr={result.pr_url or 'skipped(' + ','.join(result.skipped) + ')'}"
        ),
    }
